[settings]
experimental = true
quiet = true
locked = false

[tools]
fnox = "latest"
hk = "latest"
pitchfork = "latest"
"github:max-sixty/worktrunk" = "latest"
"npm:turbo" = "latest"

[env]
REPOSITORY_FNOX_CONFIG = ".config/fnox/local.toml"
